services:
  postgres:
    image: postgres:16-alpine
    container_name: chefitu-postgres
    environment:
      POSTGRES_DB: chefitu
      POSTGRES_USER: chefitu
      POSTGRES_PASSWORD: chefitu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
