import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

async function main() {
  await db.recipe.deleteMany();
  await db.import.deleteMany();

  await db.import.createMany({
    data: [
      {
        id: "imp_1",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-1/",
        sourceAuthorName: "fitkitchen",
        status: "ready",
        recipeId: "rec_1",
        createdAt: new Date("2026-04-20T08:00:00Z"),
        updatedAt: new Date("2026-04-20T08:01:00Z"),
      },
      {
        id: "imp_2",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-2/",
        sourceAuthorName: "dolceclub",
        status: "ready",
        recipeId: "rec_2",
        createdAt: new Date("2026-04-20T09:00:00Z"),
        updatedAt: new Date("2026-04-20T09:01:00Z"),
      },
      {
        id: "imp_3",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-3/",
        sourceAuthorName: "greenplate",
        status: "ready",
        recipeId: "rec_3",
        createdAt: new Date("2026-04-20T10:00:00Z"),
        updatedAt: new Date("2026-04-20T10:01:00Z"),
      },
      {
        id: "imp_4",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-4/",
        sourceAuthorName: "bruschettabar",
        status: "ready",
        recipeId: "rec_4",
        createdAt: new Date("2026-04-21T08:00:00Z"),
        updatedAt: new Date("2026-04-21T08:01:00Z"),
      },
      {
        id: "imp_5",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-5/",
        sourceAuthorName: "avocadolover",
        status: "ready",
        recipeId: "rec_5",
        createdAt: new Date("2026-04-21T09:00:00Z"),
        updatedAt: new Date("2026-04-21T09:01:00Z"),
      },
      {
        id: "imp_6",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-6/",
        sourceAuthorName: "italianfoodlover",
        status: "ready",
        recipeId: "rec_6",
        createdAt: new Date("2026-04-22T08:00:00Z"),
        updatedAt: new Date("2026-04-22T08:01:00Z"),
      },
      {
        id: "imp_7",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-7/",
        sourceAuthorName: "wokmaster",
        status: "ready",
        recipeId: "rec_7",
        createdAt: new Date("2026-04-22T09:00:00Z"),
        updatedAt: new Date("2026-04-22T09:01:00Z"),
      },
      {
        id: "imp_8",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-8/",
        sourceAuthorName: "overnightoats",
        status: "ready",
        recipeId: "rec_8",
        createdAt: new Date("2026-04-23T08:00:00Z"),
        updatedAt: new Date("2026-04-23T08:01:00Z"),
      },
      {
        id: "imp_9",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-9/",
        sourceAuthorName: "bakersclub",
        status: "ready",
        recipeId: "rec_9",
        createdAt: new Date("2026-04-23T09:00:00Z"),
        updatedAt: new Date("2026-04-23T09:01:00Z"),
      },
      {
        id: "imp_10",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-10/",
        sourceAuthorName: "seafoodkitchen",
        status: "ready",
        recipeId: "rec_10",
        createdAt: new Date("2026-04-24T08:00:00Z"),
        updatedAt: new Date("2026-04-24T08:01:00Z"),
      },
      {
        id: "imp_11",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-11/",
        sourceAuthorName: "sweetweekend",
        status: "processing",
        createdAt: new Date("2026-04-28T18:40:00Z"),
        updatedAt: new Date("2026-04-28T18:41:00Z"),
      },
      {
        id: "imp_12",
        sourcePlatform: "instagram",
        sourceUrl: "https://www.instagram.com/p/mock-12/",
        sourceAuthorName: "quickmeals",
        rawDescription: "So good! Full recipe in the video.",
        status: "no_recipe_in_description",
        failureReason: "No usable recipe found in the description.",
        createdAt: new Date("2026-04-28T18:50:00Z"),
        updatedAt: new Date("2026-04-28T18:51:00Z"),
      },
    ],
  });

  await db.recipe.createMany({
    data: [
      {
        id: "rec_1",
        importId: "imp_1",
        title: "Banana Oat Pancakes",
        coverImageUrl:
          "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1200&q=80",
        category: "Breakfast",
        cuisine: "Healthy",
        ingredients: [
          { amount: "2", item: "ripe bananas" },
          { amount: "2", item: "eggs" },
          { amount: "1/2", unit: "cup", item: "rolled oats" },
          { amount: "1/2", unit: "tsp", item: "baking powder" },
          { amount: "1", unit: "tsp", item: "vanilla extract" },
          { item: "pinch of cinnamon" },
        ],
        steps: [
          { order: 1, title: "Blend", instruction: "Blend all ingredients together until completely smooth." },
          { order: 2, title: "Rest", instruction: "Let the batter rest for 2 minutes so the oats absorb the liquid." },
          { order: 3, title: "Cook", instruction: "Pour small rounds onto a non-stick pan over medium-low heat. Cook 2–3 min per side until golden." },
        ],
        prepTimeMinutes: 5,
        cookTimeMinutes: 10,
        totalTimeMinutes: 15,
        servings: "2 servings",
        tags: ["Quick", "Healthy", "Gluten-free"],
        createdAt: new Date("2026-04-20T08:01:00Z"),
        updatedAt: new Date("2026-04-20T08:01:00Z"),
      },
      {
        id: "rec_2",
        importId: "imp_2",
        title: "Fudge Chocolate Brownie",
        coverImageUrl:
          "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=80",
        category: "Dessert",
        cuisine: "American",
        ingredients: [
          { amount: "200", unit: "g", item: "dark chocolate (70%)" },
          { amount: "150", unit: "g", item: "unsalted butter" },
          { amount: "200", unit: "g", item: "caster sugar" },
          { amount: "3", item: "eggs" },
          { amount: "80", unit: "g", item: "all-purpose flour" },
          { amount: "2", unit: "tbsp", item: "cocoa powder" },
          { amount: "1", unit: "tsp", item: "vanilla extract" },
          { amount: "1/2", unit: "tsp", item: "sea salt" },
        ],
        steps: [
          { order: 1, title: "Melt", instruction: "Melt chocolate and butter together in a heatproof bowl over simmering water. Stir until smooth, then cool slightly." },
          { order: 2, title: "Whisk eggs", instruction: "Beat sugar and eggs together until pale and slightly thick, about 2 minutes." },
          { order: 3, title: "Combine", instruction: "Fold the chocolate mixture into the eggs, then gently fold in flour, cocoa, vanilla, and salt. Do not overmix." },
          { order: 4, title: "Bake", instruction: "Pour into a lined 20×20 cm tin. Bake at 180°C for 22–25 min. The center should still have a slight wobble." },
          { order: 5, title: "Cool", instruction: "Let cool completely in the tin before cutting. This is key for fudgy texture." },
        ],
        prepTimeMinutes: 15,
        cookTimeMinutes: 25,
        totalTimeMinutes: 60,
        servings: "12 pieces",
        tags: ["Sweet", "Chocolate", "Crowd-pleaser"],
        createdAt: new Date("2026-04-20T09:01:00Z"),
        updatedAt: new Date("2026-04-20T09:01:00Z"),
      },
      {
        id: "rec_3",
        importId: "imp_3",
        title: "Caesar Salad with Grilled Chicken",
        coverImageUrl:
          "https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=1200&q=80",
        category: "Main",
        cuisine: "American",
        ingredients: [
          { amount: "2", item: "chicken breasts" },
          { amount: "1", item: "large romaine lettuce, chopped" },
          { amount: "1/2", unit: "cup", item: "parmesan, shaved" },
          { amount: "1", unit: "cup", item: "sourdough croutons" },
          { amount: "4", unit: "tbsp", item: "caesar dressing" },
          { amount: "1", unit: "tbsp", item: "olive oil" },
          { item: "salt and black pepper" },
        ],
        steps: [
          { order: 1, title: "Season chicken", instruction: "Rub chicken breasts with olive oil, salt, and pepper." },
          { order: 2, title: "Grill", instruction: "Grill over medium-high heat for 6–7 min per side until cooked through. Rest 5 minutes, then slice." },
          { order: 3, title: "Toss salad", instruction: "In a large bowl, toss lettuce with caesar dressing until well coated." },
          { order: 4, title: "Assemble", instruction: "Top with croutons, parmesan, and sliced chicken. Serve immediately." },
        ],
        prepTimeMinutes: 10,
        cookTimeMinutes: 15,
        totalTimeMinutes: 25,
        servings: "2 servings",
        tags: ["Healthy", "Protein", "Classic"],
        createdAt: new Date("2026-04-20T10:01:00Z"),
        updatedAt: new Date("2026-04-20T10:01:00Z"),
      },
      {
        id: "rec_4",
        importId: "imp_4",
        title: "Tomato Bruschetta",
        coverImageUrl:
          "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?auto=format&fit=crop&w=1200&q=80",
        category: "Starter",
        cuisine: "Italian",
        ingredients: [
          { amount: "4", unit: "thick slices", item: "sourdough bread" },
          { amount: "4", item: "ripe tomatoes, diced" },
          { amount: "1", item: "garlic clove" },
          { amount: "8", item: "fresh basil leaves, torn" },
          { amount: "3", unit: "tbsp", item: "extra virgin olive oil" },
          { item: "flaky sea salt and black pepper" },
        ],
        steps: [
          { order: 1, title: "Toast", instruction: "Toast the bread slices on a hot griddle or under the broiler until golden and crispy on both sides." },
          { order: 2, title: "Rub garlic", instruction: "While hot, rub each slice vigorously with the cut side of the garlic clove." },
          { order: 3, title: "Top", instruction: "Spoon the diced tomatoes onto each slice. Drizzle generously with olive oil." },
          { order: 4, title: "Finish", instruction: "Scatter basil leaves on top, season with salt and pepper. Serve straight away." },
        ],
        prepTimeMinutes: 10,
        cookTimeMinutes: 5,
        totalTimeMinutes: 15,
        servings: "4 servings",
        tags: ["Fresh", "Quick", "Vegetarian"],
        createdAt: new Date("2026-04-21T08:01:00Z"),
        updatedAt: new Date("2026-04-21T08:01:00Z"),
      },
      {
        id: "rec_5",
        importId: "imp_5",
        title: "Avocado Toast with Poached Egg",
        coverImageUrl:
          "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80",
        category: "Breakfast",
        cuisine: "Healthy",
        ingredients: [
          { amount: "2", unit: "slices", item: "sourdough bread, toasted" },
          { amount: "1", item: "ripe avocado" },
          { amount: "2", item: "eggs" },
          { amount: "1", unit: "tbsp", item: "white wine vinegar" },
          { amount: "1/2", item: "lemon, juiced" },
          { amount: "1/4", unit: "tsp", item: "chili flakes" },
          { item: "flaky salt and black pepper" },
        ],
        steps: [
          { order: 1, title: "Mash avocado", instruction: "Scoop the avocado flesh into a bowl. Add lemon juice, salt, and pepper. Mash to your preferred texture — chunky or smooth." },
          { order: 2, title: "Poach eggs", instruction: "Bring a pot of water to a gentle simmer. Add vinegar. Stir to create a vortex, then gently drop in each egg. Poach for 3 minutes for a runny yolk." },
          { order: 3, title: "Assemble", instruction: "Spread avocado generously on each toast. Place a poached egg on top." },
          { order: 4, title: "Finish", instruction: "Season with chili flakes, flaky salt, and a crack of pepper. Serve immediately." },
        ],
        prepTimeMinutes: 5,
        cookTimeMinutes: 5,
        totalTimeMinutes: 10,
        servings: "2 servings",
        tags: ["Healthy", "Vegetarian", "High-protein"],
        createdAt: new Date("2026-04-21T09:01:00Z"),
        updatedAt: new Date("2026-04-21T09:01:00Z"),
      },
      {
        id: "rec_6",
        importId: "imp_6",
        title: "Spaghetti Carbonara",
        coverImageUrl:
          "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1200&q=80",
        category: "Main",
        cuisine: "Italian",
        ingredients: [
          { amount: "400", unit: "g", item: "spaghetti" },
          { amount: "200", unit: "g", item: "guanciale or pancetta, diced" },
          { amount: "4", item: "egg yolks" },
          { amount: "1", item: "whole egg" },
          { amount: "80", unit: "g", item: "Pecorino Romano, finely grated" },
          { amount: "50", unit: "g", item: "Parmesan, finely grated" },
          { item: "coarsely ground black pepper" },
        ],
        steps: [
          { order: 1, title: "Mix sauce", instruction: "Whisk egg yolks, whole egg, Pecorino, and Parmesan together. Season generously with black pepper. Set aside." },
          { order: 2, title: "Render guanciale", instruction: "Cook guanciale in a cold pan over medium heat until the fat renders and the edges are just crispy. Remove from heat." },
          { order: 3, title: "Cook pasta", instruction: "Cook spaghetti in well-salted boiling water until al dente. Reserve 1 cup of pasta water before draining." },
          { order: 4, title: "Combine", instruction: "Add hot pasta to the pan with guanciale off the heat. Toss to coat in the fat. Wait 30 seconds, then pour in the egg mixture, tossing constantly." },
          { order: 5, title: "Finish", instruction: "Add pasta water a splash at a time, tossing vigorously, until the sauce is creamy and coats the strands. Serve immediately with extra cheese and pepper." },
        ],
        prepTimeMinutes: 10,
        cookTimeMinutes: 20,
        totalTimeMinutes: 30,
        servings: "4 servings",
        tags: ["Comfort food", "Italian", "Classic"],
        createdAt: new Date("2026-04-22T08:01:00Z"),
        updatedAt: new Date("2026-04-22T08:01:00Z"),
      },
      {
        id: "rec_7",
        importId: "imp_7",
        title: "Spicy Chicken Stir Fry",
        coverImageUrl:
          "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=80",
        category: "Main",
        cuisine: "Asian",
        ingredients: [
          { amount: "500", unit: "g", item: "chicken breast, thinly sliced" },
          { amount: "2", item: "bell peppers, sliced" },
          { amount: "1", item: "broccoli head, cut into florets" },
          { amount: "3", item: "garlic cloves, minced" },
          { amount: "1", unit: "tbsp", item: "fresh ginger, grated" },
          { amount: "3", unit: "tbsp", item: "soy sauce" },
          { amount: "1", unit: "tbsp", item: "oyster sauce" },
          { amount: "1", unit: "tbsp", item: "sriracha" },
          { amount: "1", unit: "tsp", item: "sesame oil" },
          { amount: "2", unit: "tbsp", item: "vegetable oil" },
          { amount: "1", unit: "tsp", item: "cornstarch" },
        ],
        steps: [
          { order: 1, title: "Marinate", instruction: "Toss chicken slices with cornstarch, 1 tbsp soy sauce, and a pinch of pepper. Let sit for 10 minutes." },
          { order: 2, title: "Make sauce", instruction: "Mix remaining soy sauce, oyster sauce, and sriracha in a small bowl. Set aside." },
          { order: 3, title: "Stir fry chicken", instruction: "Heat oil in a wok over high heat until smoking. Add chicken in a single layer and cook undisturbed for 90 seconds, then toss. Cook until golden. Remove and set aside." },
          { order: 4, title: "Cook vegetables", instruction: "In the same wok, stir fry garlic and ginger for 30 seconds. Add broccoli and peppers and toss over high heat for 3–4 minutes." },
          { order: 5, title: "Finish", instruction: "Return the chicken, pour in the sauce, and toss everything together for 1 minute. Drizzle with sesame oil and serve over rice." },
        ],
        prepTimeMinutes: 15,
        cookTimeMinutes: 15,
        totalTimeMinutes: 30,
        servings: "3 servings",
        tags: ["Spicy", "High-protein", "Asian"],
        createdAt: new Date("2026-04-22T09:01:00Z"),
        updatedAt: new Date("2026-04-22T09:01:00Z"),
      },
      {
        id: "rec_8",
        importId: "imp_8",
        title: "Blueberry Overnight Oats",
        coverImageUrl:
          "https://images.unsplash.com/photo-1571748982800-fa51082c2224?auto=format&fit=crop&w=1200&q=80",
        category: "Breakfast",
        cuisine: "Healthy",
        ingredients: [
          { amount: "1/2", unit: "cup", item: "rolled oats" },
          { amount: "3/4", unit: "cup", item: "oat milk (or any milk)" },
          { amount: "1/4", unit: "cup", item: "Greek yogurt" },
          { amount: "1", unit: "tbsp", item: "chia seeds" },
          { amount: "1", unit: "tbsp", item: "maple syrup or honey" },
          { amount: "1/2", unit: "cup", item: "fresh or frozen blueberries" },
          { item: "handful of granola, to top" },
        ],
        steps: [
          { order: 1, title: "Combine", instruction: "Mix oats, milk, yogurt, chia seeds, and maple syrup in a jar or bowl. Stir well." },
          { order: 2, title: "Add fruit", instruction: "Fold in half the blueberries. Mash them slightly if you want the oats to turn purple." },
          { order: 3, title: "Refrigerate", instruction: "Cover and refrigerate overnight, or for at least 4 hours." },
          { order: 4, title: "Top and serve", instruction: "In the morning, stir well. If too thick, add a splash of milk. Top with remaining blueberries and granola." },
        ],
        prepTimeMinutes: 5,
        cookTimeMinutes: 0,
        totalTimeMinutes: 5,
        servings: "1 serving",
        tags: ["Meal prep", "No-cook", "Healthy"],
        createdAt: new Date("2026-04-23T08:01:00Z"),
        updatedAt: new Date("2026-04-23T08:01:00Z"),
      },
      {
        id: "rec_9",
        importId: "imp_9",
        title: "Classic Chocolate Chip Cookies",
        coverImageUrl:
          "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=1200&q=80",
        category: "Dessert",
        cuisine: "American",
        ingredients: [
          { amount: "225", unit: "g", item: "unsalted butter, softened" },
          { amount: "200", unit: "g", item: "light brown sugar, packed" },
          { amount: "100", unit: "g", item: "white sugar" },
          { amount: "2", item: "eggs" },
          { amount: "2", unit: "tsp", item: "vanilla extract" },
          { amount: "340", unit: "g", item: "all-purpose flour" },
          { amount: "1", unit: "tsp", item: "baking soda" },
          { amount: "1", unit: "tsp", item: "sea salt" },
          { amount: "300", unit: "g", item: "chocolate chips or chunks" },
        ],
        steps: [
          { order: 1, title: "Cream butter", instruction: "Beat softened butter with both sugars until light and fluffy, about 3–4 minutes." },
          { order: 2, title: "Add eggs", instruction: "Add eggs one at a time, beating well after each. Mix in vanilla." },
          { order: 3, title: "Add dry ingredients", instruction: "Whisk flour, baking soda, and salt together, then fold into the butter mixture until just combined. Fold in chocolate chips." },
          { order: 4, title: "Chill", instruction: "Cover the dough and refrigerate for at least 1 hour (overnight gives deeper flavor)." },
          { order: 5, title: "Bake", instruction: "Roll into balls (about 60g each) and place on a lined baking sheet. Bake at 175°C for 11–13 min until edges are set but centers look underdone. They will firm up as they cool." },
        ],
        prepTimeMinutes: 15,
        cookTimeMinutes: 13,
        totalTimeMinutes: 90,
        servings: "24 cookies",
        tags: ["Baking", "Sweet", "Crowd-pleaser"],
        createdAt: new Date("2026-04-23T09:01:00Z"),
        updatedAt: new Date("2026-04-23T09:01:00Z"),
      },
      {
        id: "rec_10",
        importId: "imp_10",
        title: "Lemon Garlic Shrimp Pasta",
        coverImageUrl:
          "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=1200&q=80",
        category: "Main",
        cuisine: "Italian",
        ingredients: [
          { amount: "350", unit: "g", item: "linguine or spaghetti" },
          { amount: "400", unit: "g", item: "large shrimp, peeled and deveined" },
          { amount: "4", item: "garlic cloves, thinly sliced" },
          { amount: "1/2", unit: "tsp", item: "chili flakes" },
          { amount: "1", item: "lemon, zest and juice" },
          { amount: "4", unit: "tbsp", item: "butter" },
          { amount: "2", unit: "tbsp", item: "olive oil" },
          { amount: "handful", item: "fresh parsley, chopped" },
          { item: "salt and black pepper" },
        ],
        steps: [
          { order: 1, title: "Cook pasta", instruction: "Cook pasta in heavily salted boiling water until al dente. Reserve 1/2 cup pasta water before draining." },
          { order: 2, title: "Sear shrimp", instruction: "Season shrimp with salt and pepper. Sear in olive oil over high heat, 1–2 min per side until pink. Remove and set aside." },
          { order: 3, title: "Build sauce", instruction: "In the same pan over medium heat, add butter. Once foamy, add garlic and chili flakes. Cook for 1–2 min until fragrant but not browned." },
          { order: 4, title: "Finish", instruction: "Add lemon juice, zest, and a splash of pasta water. Toss in the pasta and shrimp. Stir to coat, adding more pasta water if needed. Finish with parsley." },
        ],
        prepTimeMinutes: 10,
        cookTimeMinutes: 20,
        totalTimeMinutes: 30,
        servings: "3 servings",
        tags: ["Seafood", "Quick", "Italian"],
        createdAt: new Date("2026-04-24T08:01:00Z"),
        updatedAt: new Date("2026-04-24T08:01:00Z"),
      },
    ],
  });

  console.log("Seeded 10 recipes.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
